# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install meson ninja-build

      - name: meson build
        run: |
          meson build

      - name: ninja
        run: |
          ninja -C build

      - name: ninja test
        run: |
          ninja -C build test

      - run: meson --reconfigure -D wfmo=false build/
      - run: ninja -C build/ test

  macOS:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip3 install meson ninja

      - name: meson build
        run: |
          meson setup build

      - name: ninja
        run: |
          meson compile -C build

      - name: ninja test
        run: |
          meson test -C build

  windows:
    runs-on: windows-latest
    env:
      CC: CL.exe
      CXX: CL.exe

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: use msvc x64 toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: build and test (msvc x64)
        uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
        with:
          action: test
          directory: build
          # options: --verbose
          meson-version: 0.64.0
          ninja-version: 1.11.1

      - name: use msvc x86 toolchain
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: build and test (msvc x86)
        uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
        with:
          action: test
          directory: build_x86
          meson-version: 0.64.0
          ninja-version: 1.11.1

